;; TODO: put directory paths into variables (see init.el).
;; capture templates
(setq org-capture-templates
      '(
        ("t" "Todo" entry (file+headline "~/Documents/gtd/todo.org" "Captured")
         "* TODO %?\n %i")
        ("f" "Food-Journal" entry (file+datetree "~/Documents/gtd/org/foodjournal.org")
         "* %?\nEntered on %U\n %i")
        ("j" "Journal" entry (file+datetree "~/Documents/gtd/org/journal.org")
         "* %?\nEntered on %U\n %i")
        ("i" "Install-Journal" entry (file "~/Documents/gtd/org/installjournal.org")
         "* %?\nEntered on %U\n %i")
        ("d" "d for diss")
        ("dt" "t for todo")
        ("dta" "allgemein" entry (file+headline "~/Projects/uni/diss/org/diss_todo.org" "Allgemein")
         "* TODO %?\n %i")
        ("dtp" "peersim" entry (file+headline "~/Projects/uni/diss/org/peersim.org" "TODOs")
         "* TODO %?\n %i")
        ("dti" "Intro" entry (file+headline "~/Projects/uni/diss/org/diss_todo.org" "Introduction")
         "* TODO %?\n %i")
        ("dts" "StrucKnol" entry (file+headline "~/Projects/uni/diss/org/diss_todo.org" "Structured Knowledge")
         "* TODO %?\n %i")
        ("dtr" "Peer Review" entry (file+headline "~/Projects/uni/diss/org/diss_todo.org" "Peer Review")
         "* TODO %?\n %i")
        ("dtb" "Background" entry (file+headline "~/Projects/uni/diss/org/diss_todo.org" "Background")
         "* TODO %?\n %i")
        ("di" "Ideas/Snippets/Thoughts dissertation" entry (file "~/Projects/uni/diss/org/ideas_dissertation.org")
         "* %?\n %i")
        ("dj" "Diss-Journal" entry (file+datetree "~/Projects/uni/diss/org/dissjournal.org")
         "* %?\nEntered on %U\n %i")
        ("m" "Memo to myself" entry (file "~/Documents/gtd/org/memos_to_myself.org")
         "* %?\n %i")
        ("p" "TODO peersim chapter" entry (file+headline "~/Projects/uni/diss/org/peersim.org" "TODOs")
         "* %?\n")
        ("b" "Useful Bash commands" entry (file "~/Documents/gtd/org/useful_bash_cmds.org")
         "* %?\n %i")
        ("r" "Recipes" entry (file "~/Documents/gtd/recipes.org")
         "* %?\n %i")
        ("a" "ACT thoughts" entry (file "~/Documents/gtd/org/act.org")
         "* %?\nEntered on %U\n %i")
        ))
